#!/usr/bin/env node
'use strict';
// soundtrack-dex: tracks you listened to while Claude Code worked get captured into a dex.
//
//   dex setup <clientId> [--port 8888]   connect Spotify (PKCE, read-only scopes)
//   dex install-statusline [--force]     point ~/.claude/settings.json statusLine here
//   dex statusline                       one-line HUD (reads local cache only)
//   dex report                           markdown summary for /dex
//   dex hook <session-start|prompt|stop> Claude Code hook entry (reads stdin JSON)

const fs = require('fs');
const path = require('path');
const http = require('http');
const crypto = require('crypto');
const { spawn } = require('child_process');

const paths = require('./lib/paths');
const store = require('./lib/store');
const game = require('./lib/game');
const spotify = require('./lib/spotify');

const NOW_PLAYING_TTL_MS = 15000;
const EVENT_FLASH_MS = 120000;
const PLAIN = process.env.DEX_PLAIN === '1';
const icon = (emoji, plain) => (PLAIN ? plain : emoji);

// ---------- helpers ----------

function readStdin(timeoutMs = 2000) {
  return new Promise((resolve) => {
    if (process.stdin.isTTY) return resolve('');
    let data = '';
    const done = () => resolve(data);
    const timer = setTimeout(done, timeoutMs);
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => (data += chunk));
    process.stdin.on('end', () => {
      clearTimeout(timer);
      done();
    });
    process.stdin.on('error', () => {
      clearTimeout(timer);
      done();
    });
  });
}

function parseJson(text) {
  try {
    return JSON.parse(text);
  } catch {
    return {};
  }
}

// Hooks must return immediately so Claude Code never waits on Spotify.
// DEX_SYNC=1 runs the worker inline (tests, debugging).
async function runWorker(args) {
  if (process.env.DEX_SYNC === '1') return worker(args);
  const child = spawn(process.execPath, [__filename, 'worker', ...args], {
    detached: true,
    stdio: 'ignore',
    windowsHide: true,
  });
  child.unref();
}

function repoName(cwd) {
  if (!cwd) return null;
  return cwd.includes('\\') ? path.win32.basename(cwd) : path.basename(cwd);
}

function writeNowPlaying(np) {
  store.writeJson(paths.nowPlayingFile(), {
    at: Date.now(),
    playing: np.playing,
    track: np.playing ? game.simplifyTrack(np.item) : null,
  });
}

// Stable entry point outside the versioned plugin dir, so the statusLine
// setting and the slash commands can find the current plugin install.
function writeLauncher() {
  store.ensureHome();
  const content = `// generated by soundtrack-dex; rewritten on every Claude Code session start\nrequire(${JSON.stringify(__filename)});\n`;
  const file = paths.launcherFile();
  let current = null;
  try {
    current = fs.readFileSync(file, 'utf8');
  } catch {}
  if (current !== content) fs.writeFileSync(file, content);
  return file;
}

function truncate(text, max) {
  const chars = Array.from(text);
  return chars.length > max ? `${chars.slice(0, max - 1).join('')}…` : text;
}

// ---------- hooks ----------

async function hook(kind) {
  const input = parseJson(await readStdin());
  if (kind === 'session-start') {
    writeLauncher();
    return;
  }
  if (!spotify.isConfigured()) return;
  const session = input.session_id || 'unknown';
  const cwd = input.cwd || process.cwd();
  const now = String(Date.now());

  if (kind === 'prompt') {
    store.update(paths.stateFile(), 'state', () => ({ turns: {} }), (s) => {
      s.turns = s.turns || {};
      const cutoff = Date.now() - 12 * 3600 * 1000;
      for (const [id, t] of Object.entries(s.turns)) if (t.start < cutoff) delete s.turns[id];
      s.turns[session] = { start: Number(now), cwd };
    });
    await runWorker(['start', session, now]);
  } else if (kind === 'stop') {
    await runWorker(['stop', session, cwd, now]);
  }
}

// ---------- worker (detached) ----------

async function worker([kind, session, ...rest]) {
  try {
    if (kind === 'start') {
      const np = await spotify.currentlyPlaying();
      writeNowPlaying(np);
      if (!np.playing) return;
      const track = game.simplifyTrack(np.item);
      store.update(paths.stateFile(), 'state', () => ({ turns: {} }), (s) => {
        const turn = s.turns && s.turns[session];
        if (turn && track) turn.startTrack = track;
      });
    } else if (kind === 'stop') {
      await captureTurn(session, rest[0], Number(rest[1]) || Date.now());
    } else if (kind === 'refresh') {
      try {
        writeNowPlaying(await spotify.currentlyPlaying());
      } finally {
        try { fs.unlinkSync(paths.lockFile('refresh')); } catch {}
      }
    }
  } catch (err) {
    store.log(`worker ${kind}`, err);
  }
}

async function captureTurn(session, cwd, endedAt) {
  const state = store.readJson(paths.stateFile(), { turns: {} });
  const turn = (state.turns || {})[session];
  const start = turn ? turn.start : endedAt;

  const [recent, np] = await Promise.all([spotify.recentlyPlayed(start), spotify.currentlyPlaying()]);
  writeNowPlaying(np);

  const found = new Map();
  for (const entry of recent) {
    if (Date.parse(entry.played_at) < start) continue;
    const t = game.simplifyTrack(entry.track);
    if (t) found.set(t.id, t);
  }
  if (turn && turn.startTrack) found.set(turn.startTrack.id, turn.startTrack);
  if (np.playing) {
    const t = game.simplifyTrack(np.item);
    if (t) found.set(t.id, t);
  }

  const day = game.dayKey(new Date(endedAt));
  const at = new Date(endedAt).toISOString();
  const repo = repoName(cwd || (turn && turn.cwd));

  if (found.size > 0) {
    store.update(paths.dbFile(), 'db', game.emptyDb, (db) => {
      const events = [];
      for (const t of found.values()) {
        const ev = game.capture(db, t, { day, at, repo });
        if (ev) events.push(ev);
      }
      game.markActiveDay(db, day);
      game.pushEvents(db, events);
    });
  }
  store.update(paths.stateFile(), 'state', () => ({ turns: {} }), (s) => {
    if (s.turns) delete s.turns[session];
  });
}

// ---------- statusline ----------

function maybeRefresh() {
  const lock = paths.lockFile('refresh');
  try {
    if (Date.now() - fs.statSync(lock).mtimeMs < 20000) return;
    fs.unlinkSync(lock);
  } catch {}
  try {
    store.ensureHome();
    fs.closeSync(fs.openSync(lock, 'wx'));
  } catch {
    return;
  }
  runWorker(['refresh', '-']);
}

function statuslineText() {
  if (!spotify.isConfigured()) return `${icon('♫', '~')} dex: /dex-setup 필요`;

  const np = store.readJson(paths.nowPlayingFile(), null);
  if (!np || Date.now() - np.at > NOW_PLAYING_TTL_MS) maybeRefresh();

  const db = store.readJson(paths.dbFile(), game.emptyDb());
  const parts = [];

  if (np && np.playing && np.track) {
    const title = truncate(`${game.artistLine(np.track)} — ${np.track.name}`, 42);
    const card = db.tracks[np.track.id];
    const days = card ? card.days.length : 0;
    const lv = game.levelOf(days);
    const tag = card ? `[${game.levelName(lv)} Lv${lv} · ${days}일]` : '[미포획]';
    parts.push(`${icon('♫', '~')} ${title} ${tag}`);
  } else {
    parts.push(`${icon('♫', '~')} —`);
  }

  parts.push(`${icon('📖', 'dex')} ${Object.keys(db.tracks).length}`);
  const s = game.streak(db);
  if (s > 0) parts.push(`${icon('🔥', 'streak')} ${s}일`);

  const last = db.events[db.events.length - 1];
  if (last && Date.now() - Date.parse(last.at) < EVENT_FLASH_MS) {
    parts.push(last.type === 'new' ? icon('✨NEW', '*NEW') : `${icon('⬆', '^')} ${game.levelName(last.level)} 승급`);
  }
  return parts.join(' │ ');
}

async function statusline() {
  await readStdin(500); // Claude Code sends session JSON; not needed yet.
  let line;
  try {
    line = statuslineText();
  } catch (err) {
    store.log('statusline', err);
    line = `${icon('♫', '~')} dex 오류 (dex.log 확인)`;
  }
  process.stdout.write(`${line}\n`);
}

// ---------- report (/dex) ----------

function report() {
  if (!spotify.isConfigured()) {
    console.log('Spotify가 아직 연결 안 됨. `/dex-setup <Client ID>`로 연결해.');
    return;
  }
  const db = store.readJson(paths.dbFile(), game.emptyDb());
  const cards = Object.values(db.tracks);
  const today = game.dayKey();
  const artists = new Set(cards.flatMap((c) => c.artists.map((a) => a.name)));

  const lines = [];
  lines.push(`# 📖 코딩 사운드트랙 도감 — ${cards.length}곡 · 아티스트 ${artists.size}명 · 🔥 ${game.streak(db)}일`);

  const todays = cards.filter((c) => c.days.includes(today));
  const newToday = todays.filter((c) => game.dayKey(new Date(c.firstCaptured)) === today);
  lines.push('', `오늘 포획 ${todays.length}곡 (신규 ${newToday.length})`);

  const byLevel = game.LEVELS.map((l, i) => `${l.name} ${cards.filter((c) => game.levelOf(c.days.length) === i + 1).length}`);
  lines.push(`등급: ${byLevel.reverse().join(' · ')}`);

  const fmt = (c) => `${c.name} — ${game.artistLine(c)}`;

  const near = cards
    .map((c) => ({ c, next: game.nextLevel(c.days.length) }))
    .filter((x) => x.next && x.next.remaining === 1)
    .sort((a, b) => b.c.days.length - a.c.days.length)
    .slice(0, 5);
  if (near.length) {
    lines.push('', '## 승급 임박 (하루만 더)');
    near.forEach(({ c, next }) => lines.push(`- ${fmt(c)} → ${next.name}`));
  }

  const top = [...cards].sort((a, b) => b.days.length - a.days.length || b.turns - a.turns).slice(0, 5);
  if (top.length) {
    lines.push('', '## 가장 오래 함께한 곡');
    top.forEach((c) => {
      const lv = game.levelOf(c.days.length);
      lines.push(`- ${fmt(c)} · ${game.levelName(lv)} Lv${lv} · ${c.days.length}일 · 턴 ${c.turns}`);
    });
  }

  const recent = [...cards].sort((a, b) => Date.parse(b.firstCaptured) - Date.parse(a.firstCaptured)).slice(0, 5);
  if (recent.length) {
    lines.push('', '## 최근 새로 들어온 곡');
    recent.forEach((c) => lines.push(`- ${fmt(c)} (${game.dayKey(new Date(c.firstCaptured))})`));
  }

  if (!cards.length) lines.push('', '아직 포획한 곡이 없음. 음악 틀고 Claude Code에 작업 하나 시켜봐.');
  console.log(lines.join('\n'));
}

// ---------- setup ----------

function openBrowser(url) {
  if (process.env.DEX_NO_BROWSER === '1') return;
  const [cmd, args] =
    process.platform === 'win32'
      ? ['rundll32', ['url.dll,FileProtocolHandler', url]] // cmd "start" would split on '&'
      : process.platform === 'darwin'
        ? ['open', [url]]
        : ['xdg-open', [url]];
  try {
    spawn(cmd, args, { detached: true, stdio: 'ignore', windowsHide: true }).unref();
  } catch {}
}

function waitForCallback(port, expectedState, timeoutMs) {
  return new Promise((resolve, reject) => {
    const server = http.createServer((req, res) => {
      const url = new URL(req.url, `http://127.0.0.1:${port}`);
      if (url.pathname !== '/callback') {
        res.writeHead(404).end();
        return;
      }
      const error = url.searchParams.get('error');
      const ok = !error && url.searchParams.get('state') === expectedState && url.searchParams.get('code');
      res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(ok ? '<h2>soundtrack-dex 연결 완료. 이 창은 닫아도 돼.</h2>' : `<h2>연결 실패: ${error || 'state 불일치'}</h2>`);
      clearTimeout(timer);
      server.close();
      ok ? resolve(url.searchParams.get('code')) : reject(new Error(error || 'state mismatch'));
    });
    const timer = setTimeout(() => {
      server.close();
      reject(new Error('시간 초과: 브라우저에서 승인이 안 끝났어'));
    }, timeoutMs);
    server.on('error', (err) => {
      clearTimeout(timer);
      reject(err.code === 'EADDRINUSE' ? new Error(`포트 ${port} 사용 중. --port 로 다른 포트를 지정하고 대시보드 Redirect URI도 바꿔`) : err);
    });
    server.listen(port, '127.0.0.1');
  });
}

async function setup(args) {
  const portIdx = args.indexOf('--port');
  const port = portIdx >= 0 ? Number(args[portIdx + 1]) : 8888;
  const existing = spotify.readConfig() || {};
  const positional = args.filter((a, i) => !a.startsWith('--') && !(portIdx >= 0 && i === portIdx + 1));
  const clientId = positional[0] || existing.clientId;
  if (!clientId) {
    console.log('사용법: dex setup <Spotify Client ID> [--port 8888]');
    process.exitCode = 1;
    return;
  }
  const redirectUri = `http://127.0.0.1:${port}/callback`;
  const { verifier, challenge } = spotify.pkcePair();
  const state = crypto.randomBytes(16).toString('hex');
  const url = spotify.authorizeUrl({ clientId, redirectUri, challenge, state });

  console.log(`Redirect URI (Spotify 대시보드에 등록돼 있어야 함): ${redirectUri}`);
  console.log(`브라우저에서 승인해줘:\n${url}\n`);
  const pending = waitForCallback(port, state, 180000);
  openBrowser(url);
  const code = await pending;

  const tokens = await spotify.postToken({
    grant_type: 'authorization_code',
    code,
    redirect_uri: redirectUri,
    client_id: clientId,
    code_verifier: verifier,
  });
  store.update(paths.configFile(), 'config', () => ({}), (c) => {
    c.clientId = clientId;
    c.redirectUri = redirectUri;
  });
  spotify.saveTokens(tokens);
  writeLauncher();

  const np = await spotify.currentlyPlaying();
  writeNowPlaying(np);
  console.log('연결 완료.');
  console.log(np.playing ? `지금 재생 중: ${game.artistLine(np.item)} — ${np.item.name}` : '지금은 재생 중인 곡 없음.');
  console.log(`데이터 위치: ${paths.dexHome()}`);
}

// ---------- install-statusline ----------

function installStatusline(args) {
  const launcher = writeLauncher().replace(/\\/g, '/');
  const command = `node "${launcher}" statusline`;
  const file = paths.claudeSettingsFile();
  const settings = store.readJson(file, {});
  const current = settings.statusLine;
  const ours = current && typeof current.command === 'string' && current.command.includes('soundtrack-dex');

  if (current && !ours && !args.includes('--force')) {
    console.log(`이미 다른 statusLine이 있어: ${JSON.stringify(current)}`);
    console.log('덮어쓰려면 --force (기존 설정은 settings.json.dex-backup 에 백업됨)');
    process.exitCode = 1;
    return;
  }
  if (fs.existsSync(file)) fs.copyFileSync(file, `${file}.dex-backup`);
  settings.statusLine = { type: 'command', command, padding: 0 };
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, `${JSON.stringify(settings, null, 2)}\n`);
  console.log(`statusLine 설정 완료 → ${file}`);
  console.log(`command: ${command}`);
}

// ---------- main ----------

async function main() {
  const [cmd, ...args] = process.argv.slice(2);
  switch (cmd) {
    case 'hook':
      try {
        await hook(args[0]);
      } catch (err) {
        store.log(`hook ${args[0]}`, err); // never break Claude Code
      }
      return;
    case 'worker':
      return worker(args);
    case 'statusline':
      return statusline();
    case 'report':
      return report();
    case 'setup':
      return setup(args);
    case 'install-statusline':
      return installStatusline(args);
    case 'launcher':
      console.log(writeLauncher());
      return;
    default:
      console.log('dex <setup|install-statusline|statusline|report|launcher>');
  }
}

main().catch((err) => {
  console.error(err.message || err);
  process.exitCode = 1;
});
